### ISSUE TITLE
Support for AWS Bedrock & Azure Openai

### ISSUE THREAD

**Issue by vbeutner** [pyember/ember#17]
Is there support for these providers and if yes, is there a way I should set these in the Ember Configuration System?

For example something like this:
```
registry:
  providers:
    bedrock:
      enabled: true
      api_keys:
        default:
          key: "${OPENAI_API_KEY}"
```
